# Generated by Django 4.2.6 on 2024-05-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_actors_alter_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='tmdb_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='tmdb_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
