# Generated by Django 4.2.6 on 2024-05-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_actor_tmdb_id_director_tmdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies', to='movies.genre'),
        ),
    ]
