# Generated by Django 4.2.6 on 2024-05-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_movie_genre_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile_image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='profile_image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
