# Generated by Django 4.2.7 on 2024-05-22 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_actor_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='talks_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes_count',
        ),
    ]
