# Generated by Django 4.2.6 on 2024-05-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_actor_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
