# Generated by Django 4.2.7 on 2024-05-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_remove_movie_likes_count_remove_movie_talks_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_reviews/'),
        ),
    ]
