# Generated by Django 4.2.7 on 2024-05-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_review_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
