# Generated by Django 4.2.6 on 2024-05-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_tmdb_id'),
        ('movies', '0011_alter_movie_tmdb_id'),
    ]

    operations = [
    ]
