# Generated by Django 4.2.7 on 2024-05-23 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0012_merge_20240523_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='movietalklike',
            name='movie_talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='movies.talk'),
        ),
        migrations.AlterField(
            model_name='movietalkreply',
            name='movie_talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='movies.talk'),
        ),
        migrations.DeleteModel(
            name='MovieTalk',
        ),
    ]
