# Generated by Django 4.2.7 on 2024-05-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_talk_alter_movietalklike_movie_talk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
