# Generated by Django 4.2.6 on 2024-05-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_merge_20240523_1428'),
        ('movies', '0015_movie_talks_count'),
    ]

    operations = [
    ]
